# Generated by Django 5.1.6 on 2025-08-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_roomimage_room_type_roomimage_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_imags', to='rooms.roomtype'),
        ),
    ]
