# Generated by Django 5.2.3 on 2025-08-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomimage_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
    ]
