# Generated by Django 5.2.3 on 2025-08-03 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_roomtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
