# Generated by Django 5.2.3 on 2025-08-03 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_roomtype_options_roomtype_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
