# Generated by Django 5.2 on 2025-08-10 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_roomtype_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='per_day_charges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.booking')),
            ],
        ),
    ]
