# Generated by Django 5.2 on 2025-08-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_booking_status_roomtype_per_day_charges_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
